### ISSUE TITLE
Form of the returned matrix

### ISSUE THREAD

**Issue by jfhc** [msuchard/MultiBD#4]
Hi, I'm not 100% clear on the form of the returned matrix - am I right in thinking that after running

`mat <- dbd_prob(  ... a0 = 2, b0 = 5 ...)` 

(with all the other parameters)

Then `mat[1,7]` will be the probability of going from state (2,5) to state (0,6) (in the given time and with the given parameters)? And `mat[3,9]` would be the probability of going to state (2,8)?

I'm a bit confused because in the 'short example' in the readme, the indexing is done like 
`[1, data$I[k + 1] + 1]                 # To: S(t_(k+1)), I(t_(k+1))`

and I don't completely understand what's going on here, particularly why the first index is 1.

**Comment by lamho86** [comment]
Hi,

The return matrix is the transition probabilities from `(a0, b0)` to `(a:a0, 0:B)`.
In other word, `mat[i,j]` is the transition probability from `(a0, b0)` to `(a+i-1, j-1)`.
In the example, `a = data$S[k + 1]`. So, `mat[1, data$I[k + 1] + 1]` is the transition probability to `(data$S[k + 1], data$I[k + 1]) # To: S(t_(k+1)), I(t_(k+1))`.

This complication arises because the matrix in R always starts with index 1.
